# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: DawsonVerley # jekyll-seo-tag > Owners twitter username
author: DawsonVerley # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Dawson Verley # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/DawsonVerley
    - https://github.com/dawsonv

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Blog # Needed for Siteleaf
    output: true
    description: "A blog for what I'm up to and the stuff I'm interested in." # The post list page content
    feature_text: |
      Loading Creative Title (This could take a while...)
    feature_image: /assets/images/banner.jpg

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/default-social-image.png # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
remote_theme: daviddarnes/alembic
title: Dawson A. Verley # Site name or title, also used in jekyll-seo-tag
logo: /assets/images/logo.png # Site logo, also used in jekyll-seo-tag
description: Dawson's personal website. Read about projects, passions, and more.
url: https://dawsonv.github.io # Site url, also used in jekyll-seo-tag
baseurl: ""
email: "dawsonv7@gmail.com"
service_worker: false # turns off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site navigation
navigation_header:
  Home: /
  About: /about/
  Projects: /projects/
  Blog: /blog/
  Search: /search/

navigation_footer:
  Base Web Design by David Darnes: https://darn.es

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/DawsonVerley
  GitHub: https://github.com/dawsonv
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  #Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  Reddit: "#FF4500"
  Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  Email: "#FF0000"
